repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [file, python]
    - id: pycln
      name: pycln
      entry: poetry run pycln
      language: system
      types: [file, python]
    - id: isort
      args: ["--profile", "black", "--filter-files"]
      name: isort
      entry: poetry run isort
      language: system
      types: [file, python]
